/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/ui/Alert.vue')['default']
    AlertMapPanel: typeof import('./components/AlertMapPanel.vue')['default']
    Button: typeof import('./components/ui/Button.vue')['default']
    ExtendedImage: typeof import('./components/ui/ExtendedImage.vue')['default']
    Image: typeof import('./components/ui/Image.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabs: typeof import('./components/ui/Tabs.vue')['default']
    TabsContent: typeof import('./components/ui/TabsContent.vue')['default']
    TabsTrigger: typeof import('./components/ui/TabsTrigger.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    WarningSystem: typeof import('./components/WarningSystem.vue')['default']
  }
}
