/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/ui/Alert.vue')['default']
    AlertMapPanel: typeof import('./components/AlertMapPanel.vue')['default']
    Button: typeof import('./components/ui/Button.vue')['default']
    Checkbox: typeof import('./components/ui/Checkbox.vue')['default']
    CheckboxExample: typeof import('./components/ui/CheckboxExample.vue')['default']
    Dropdown: typeof import('./components/ui/Dropdown.vue')['default']
    DropdownExample: typeof import('./components/ui/DropdownExample.vue')['default']
    DropdownItem: typeof import('./components/ui/DropdownItem.vue')['default']
    ExtendedImage: typeof import('./components/ui/ExtendedImage.vue')['default']
    Modal: typeof import('./components/ui/Modal.vue')['default']
    ModalExample: typeof import('./components/ui/ModalExample.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabs: typeof import('./components/ui/Tabs.vue')['default']
    TabsContent: typeof import('./components/ui/TabsContent.vue')['default']
    TabsTrigger: typeof import('./components/ui/TabsTrigger.vue')['default']
    Toast: typeof import('./components/ui/Toast.vue')['default']
    ToastProvider: typeof import('./components/ui/ToastProvider.vue')['default']
  }
}
